---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: https://api.netlify.com/build_hooks/5e1c995c83ae738773a44299
sections:
- type: document
  path: welcome.md
  label: Accueil
- type: document
  path: a-propos.md
  label: À propos
- type: document
  path: mentions-legales.md
  label: Mentions légales
- type: directory
  path: blog
  label: Blog
  create: all
  match: "**/*"
  templates:
  - blog-post
- type: heading
  label: Sections
- type: directory
  path: authors
  label: Authors
  create: documents
  match: "**/*"
  templates:
  - auteur
- type: heading
  label: Configuration
- type: document
  path: settings/global.yml
  label: Paramètres
- type: document
  path: settings/navigation.yml
  label: Navigation
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
