---
label: _base
hide_body: true
display_field: title
fields:
- name: title
  type: text
  config:
    required: true
  label: Titre
  description: Pour SEO optimal, ne pas dépasser 70 caractères.
- name: author
  type: select
  default: authors/guidoline.md
  config:
    required: false
    options: []
    source:
      type: pages
      section: authors
      file: 
      path: 
  label: Auteur
- name: published
  type: datetime
  label: Date de publication
  description: ''
  config:
    required: false
    date_format: DD/MM/YYYY
    time_format: h:mm
    display_utc: false
  default: now
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: Description
  description: Pour un SEO optimal, ne pas dépasser 160 caractères
- name: groupe
  type: field_group
  config: {}
  fields:
  - name: a
    type: text
    config:
      required: false
    label: A
  - name: b
    type: text
    config:
      required: false
    label: B
  label: Groupe
