---
label: configuration.settings
hide_body: true
fields:
- name: name
  type: text
  config:
    required: false
  label: Nom du site
- name: url
  type: text
  config:
    required: false
  label: URL
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description
- name: credits
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Crédits
- name: categories
  type: tag_list
  default: []
  label: Catégories
