---
label: configuration.theme
hide_body: true
fields:
- name: name
  type: text
  config:
    required: false
  label: Nom du site
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description
